### PR TITLE
DF-2551 - extend url validator to accept unicode characters

### PR DESCRIPTION
**Pull request by mdavidovski**
Basically I just extend the regex with u00C0 - uffff. Please check if that is what we want, in regards to business logic.

### CODE REVIEW

**Comment by gallm** [comment]
ok

**Comment by emina-str** [comment]
@gallm , @mdavidovski  
I'm not sure is it all we wanted, I've checked out the PR, and the URL validator works if we copy/past the URL link from f.e. wikipedia : 
`https://en.wikipedia.org/wiki/Fr%C3%A9d%C3%A9ric_Chopin`
but if somebody decides to actually write a link down, he won't use those unicode symbols, then actual :
`https://en.wikipedia.org/wiki/Frédéric_Chopin`

then the validator still doesn't allow it.
image

Is it acceptable, or we need both case covered?

**Comment by gallm** [comment]
@emina-str , @mdavidovski 
Hi Emina, thanks for hint. In my opionion it should work for both cases. And still I wonder if we need a validator at all. I would suggest to spent 2 more hours on this topic. If we come up with a solution - great! If not make it a simple text-field. We can always fix this issue afterwards.

**Comment by mdavidovski** [comment]
@emina-str it should work now. It seems I didn't fix the validation for the second part of the URL, after ".com/"

**Pull request merged**
