### PR TITLE
DF-2747 Extend url validator to except commas

### PR DESCRIPTION
**Pull request by mdavidovski**

### CODE REVIEW

**Review by seco-mgabor — CHANGES_REQUESTED** [review]
Unit test is missing.
I've tried to test the URL from the issue on emailregex.com, but the regex did not match. :(

**Comment by ganqqwerty** [comment]
some tests would be cool

**Comment by mdavidovski** [comment]
> Unit test is missing.
> I've tried to test the URL from the issue on emailregex.com, but the regex did not match. :(

Hi Marius, 
I will add a test for the comma logic, but I am not sure what you mean with the "URL doesn't match in emailregex.com"?
I tried it there and it works for me, but I have never used it before and I might be doing it wrong. 
Here is a screenshot of how I used it...
Screenshot 2020-09-07 at 19 53 35

**Comment by mdavidovski** [comment]
> some tests would be cool

Hi Yuri,
Yeah, I figured it's just a small change and didn't do it, sorry.
Can you please tell me where you test all other pattern validations, so I can add the test?

**Review by c-linse — APPROVED** [review]

**Review by seco-mgabor — APPROVED** [review]

**Review by seco-mgabor — APPROVED** [review]

**Pull request merged**
